
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async register(payload: RegisterRequest) : Promise<Result<RegisterResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async login(payload: LoginRequest) : Promise<Result<LoginResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout() : Promise<Result<null, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentSession() : Promise<Result<UserSession | null, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkAccessToken(accessToken: string) : Promise<boolean> {
    return await TAURI_INVOKE("check_access_token", { accessToken });
},
async deleteRefreshToken(account: string) : Promise<Result<null, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_refresh_token", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDailyQuests() : Promise<Result<UserQuestStatusResponse[], ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_daily_quests") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitQuestProof(questUlid: string, payload: SubmitProofRequest, imageList: number[][] | null, audioList: number[][] | null) : Promise<Result<SubmitProofResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_quest_proof", { questUlid, payload, imageList, audioList }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProofFeed(limit: number | null, offset: number | null) : Promise<Result<ProofFeedResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_proof_feed", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProofDetails(proofUlid: string) : Promise<Result<ProofDetailsResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_proof_details", { proofUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleProofBelief(proofUlid: string) : Promise<Result<null, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_proof_belief", { proofUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSomeoneJournal(userUlid: string) : Promise<Result<ProofDetailsResponse[], ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_someone_journal", { userUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMyJournal() : Promise<Result<ProofDetailsResponse[], ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_my_journal") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLobby(name: string, topic: string, description: string | null) : Promise<Result<LobbyDto, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_lobby", { name, topic, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllLobbies() : Promise<Result<LobbyFeedResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_lobbies") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLobbyDetail(lobbyUlid: string) : Promise<Result<LobbyDetailsResponse, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lobby_detail", { lobbyUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLobbyMemebersCount(lobbyUlid: string) : Promise<Result<number, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lobby_memebers_count", { lobbyUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinLobby(lobbyUlid: string) : Promise<Result<LobbyMemberDto, ErrorBody>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_lobby", { lobbyUlid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Complexity = "easy" | "medium" | "hard"
export type ErrorBody = { error_type: ErrorCode; message: string }
export type ErrorCode = "AUTH_INVALID" | "USER_EXISTS" | "VALIDATION_ERROR" | "NOT_FOUND" | "DATABASE_ERROR" | "SERVER_ERROR" | "CUSTOM_ERROR"
export type LobbyDetailsResponse = { lobby: LobbyDto; members_count: number }
export type LobbyDto = { ulid: string; name: string; topic: string; description: string | null; owner_id: string; created_at: string }
export type LobbyFeedItem = { lobby: LobbyDto; is_member: boolean }
export type LobbyFeedResponse = { items: LobbyFeedItem[] }
export type LobbyMemberDto = { lobby_id: string; user_id: string; role: Role; joined_at: string }
export type LoginRequest = { password: string; email: string }
export type LoginResponse = { ulid: string; username: string; email: string; refresh_token: string; level: number; avatar_url: string | null }
export type ProofDetailsResponse = { ulid: string; user_id: string; username: string; avatar_url: string | null; quest_id: string; quest_title: string; quest_description: string | null; xp_reward: number; proof_text: string | null; status: string; photo_urls: string[]; voice_urls: string[]; beliefs_count: number; is_believed: boolean; created_at: string }
export type ProofFeedResponse = { items: ProofDetailsResponse[]; has_more: boolean; next_offset: number }
export type QuestDto = { ulid: string; title: string; description: string | null; complexity: Complexity; xp_reward: number; validation_type: string; target_value: number }
export type QuestStatus = "IN_PROGRESS" | "COMPLETED" | "IN_PENDING" | "FAILED"
export type RegisterRequest = { username: string; email: string; password: string }
export type RegisterResponse = { ulid: string; username: string; email: string; created_at: string; refresh_token: string; level: number; avatar_url: string | null }
export type Role = "STRANGER" | "MEMBER" | "HELPER" | "MODERATOR" | "ADMIN"
export type SubmitProofRequest = { proof_text: string | null; photo_count: number; voice_count: number }
export type SubmitProofResponse = { proof_ulid: string; status: string; photo_upload_urls: string[]; voice_upload_urls: string[] }
export type UserQuestStatusResponse = { user_ulid: string; quest: QuestDto; status: QuestStatus; current_value: number; is_completed: boolean; completed_at: string | null }
export type UserSession = { access_token: string | null; user_ulid: string; email: string; username: string; level: number; avatar_url: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
